### ISSUE TITLE
Life Preserver: replication failed without explanation

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lpreserver#1]
First run of my first replication. 

Some time after 807M was written to the remote dataset, replication failed. Only 432K remained. 

The source dataset uses PersonaCrypt but at the time of the failure, I was not logged in as that user. Wired LAN in use, two routers in the same room. 

The _without explanation_ aspect probably belongs under https://github.com/trueos/sysadm-ui-qt/issues but first, let's troubleshoot this failure (I found Life Preserver in PC-BSD CURRENT to be dreadfully unreliable; my #1 area of concern).

**Comment by grahamperrin** [comment]
Setting aside SysAdm and temporarily removing remote storage from the mix, things become clearer: 

```
[bbsadmin-l@momh167-gjp4-macbookpro112-trueos] ~% sudo zfs send persona_gjp4@2016-08-11-18-18 | sudo zfs receive -F tank/gjp4
warning: cannot send 'persona_gjp4@2016-08-11-18-18': Input/output error
cannot receive new filesystem stream: checksum mismatch or incomplete stream
[bbsadmin-l@momh167-gjp4-macbookpro112-trueos] ~%
```

I knew long ago that the source pool, on a USB flash drive, included data errors but when last used – when last scrubbed – all errors were within snapshots that I did not expect to be included with a (reinitialising) send and receive. I should perform another scrub but not before I attempt a 'lazy' backup (one that will be less strict than a ZFS send and receive operation).

**Comment by kmoore134** [comment]
Yea, this particular error looks bad, input/output errors are from the source and will prevent lpreserver from doing anything meaningful.
